export const painDescriptions = [
  "sharp",
  "shocking",
  "stinging",
  "electric",
  "cramping",
  "dull",
  "pinching",
  "penetrating",
  "burning",
  "radiating",
  "aching",
  "throbbing",
  "pressing",
  "pulsating",
  "shooting",
  "pins/needles",
  "tingling",
  "stabbing"
];

export const timezoneOptions = [
  { disabled: false, value: "America/New York", name: "(GMT-0400) America/New_York" },
  { disabled: true, value: "", name: "--------------------" },
  { disabled: false, value: "America/Chicago", name: "(GMT-0500) America/Chicago" },
  { disabled: true, value: "", name: "--------------------" },
  { disabled: false, value: "US/Hawaii", name: "(GMT-1000) Hawaii" },
  { disabled: false, value: "US/Alaska", name: "(GMT-0800) Alaska" },
  { disabled: false, value: "US/Pacific", name: "(GMT-0700) Pacific Time (US &amp; Canada)" },
  { disabled: false, value: "US/Arizona", name: "(GMT-0700) Arizona" },
  { disabled: false, value: "US/Mountain", name: "(GMT-0600) Mountain Time (US &amp; Canada)" },
  { disabled: false, value: "US/Central", name: "(GMT-0500) Central Time (US &amp; Canada)" },
  { disabled: false, value: "US/Eastern", name: "(GMT-0400) Eastern Time (US &amp; Canada)" },
  { disabled: false, value: "US/East-Indiana", name: "(GMT-0400) Indiana (East)" },
  { disabled: true, value: "", name: "--------------------" },
  { disabled: false, value: "Pacific/Midway", name: "(GMT-1100) International Date Line West" },
  { disabled: false, value: "Pacific/Midway", name: "(GMT-1100) Midway Island" },
  { disabled: false, value: "Pacific/Samoa", name: "(GMT-1100) Samoa" },
  { disabled: false, value: "US/Hawaii", name: "(GMT-1000) Hawaii" },
  { disabled: false, value: "US/Alaska", name: "(GMT-0800) Alaska" },
  { disabled: false, value: "US/Pacific", name: "(GMT-0700) Pacific Time (US &amp; Canada)" },
  { disabled: false, value: "America/Tijuana", name: "(GMT-0700) Tijuana" },
  { disabled: false, value: "US/Arizona", name: "(GMT-0700) Arizona" },
  { disabled: false, value: "America/Chihuahua", name: "(GMT-0600) Chihuahua" },
  { disabled: false, value: "America/Mazatlan", name: "(GMT-0600) Mazatlan" },
  { disabled: false, value: "US/Mountain", name: "(GMT-0600) Mountain Time (US &amp; Canada)" },
  { disabled: false, value: "Canada/Saskatchewan", name: "(GMT-0600) Saskatchewan" },
  { disabled: false, value: "US/Central", name: "(GMT-0500) Central Time (US &amp; Canada)" },
  { disabled: false, value: "Canada/Central", name: "(GMT-0500) Central America" },
  { disabled: false, value: "Canada/Central", name: "(GMT-0500) Central Time (US &amp; Canada)" },
  { disabled: false, value: "Mexico/General", name: "(GMT-0500) Guadalajara" },
  { disabled: false, value: "Mexico/General", name: "(GMT-0500) Mexico City" },
  { disabled: false, value: "America/Monterrey", name: "(GMT-0500) Monterrey" },
  { disabled: false, value: "America/Bogota", name: "(GMT-0500) Bogota" },
  { disabled: false, value: "America/Lima", name: "(GMT-0500) Lima" },
  { disabled: false, value: "America/Rio_Branco", name: "(GMT-0500) Rio Branco" },
  { disabled: false, value: "Etc/GMT+5", name: "(GMT-0500) Quito" },
  { disabled: false, value: "US/Eastern", name: "(GMT-0400) Eastern Time (US &amp; Canada)" },
  { disabled: false, value: "US/East-Indiana", name: "(GMT-0400) Indiana (East)" },
  { disabled: false, value: "America/Caracas", name: "(GMT-0400) Caracas" },
  { disabled: false, value: "Etc/GMT+4", name: "(GMT-0400) La Paz" },
  { disabled: false, value: "America/Cuiaba", name: "(GMT-0400) Cuiaba" },
  { disabled: false, value: "America/Manaus", name: "(GMT-0400) Manaus" },
  { disabled: false, value: "America/Santiago", name: "(GMT-0400) Santiago" },
  { disabled: false, value: "America/Cuiaba", name: "(GMT-0400) Mato Grosso" },
  { disabled: false, value: "America/Guyana", name: "(GMT-0400) Georgetown" },
  { disabled: false, value: "Canada/Atlantic", name: "(GMT-0300) Atlantic Time (Canada)" },
  { disabled: false, value: "America/Argentina/Buenos_Aires", name: "(GMT-0300) Buenos Aires" },
  { disabled: false, value: "America/Fortaleza", name: "(GMT-0300) NE Brazil, Fortaleza" },
  { disabled: false, value: "America/Sao_Paulo", name: "(GMT-0300) Brasilia, Sao Paulo" },
  { disabled: false, value: "America/Godthab", name: "(GMT-0200) Greenland" },
  { disabled: false, value: "America/Noronha", name: "(GMT-0200) Fernando de Noronha" },
  { disabled: false, value: "Canada/Newfoundland", name: "(GMT-0230) Newfoundland" },
  { disabled: false, value: "Atlantic/Cape_Verde", name: "(GMT-0100) Cape Verde Is. " },
  { disabled: false, value: "Atlantic/Azores", name: "(GMT+0000) Azores" },
  { disabled: false, value: "Africa/Casablanca", name: "(GMT+0000) Casablanca" },
  { disabled: false, value: "Europe/Dublin", name: "(GMT+0100) Dublin" },
  { disabled: false, value: "Europe/London", name: "(GMT+0100) Edinburgh" },
  { disabled: false, value: "Europe/Lisbon", name: "(GMT+0100) Lisbon" },
  { disabled: false, value: "Europe/London", name: "(GMT+0100) London" },
  { disabled: false, value: "Africa/Monrovia", name: "(GMT+0000) Monrovia" },
  { disabled: false, value: "UTC", name: "(GMT+0000) UTC" },
  { disabled: false, value: "Europe/Amsterdam", name: "(GMT+0200) Amsterdam" },
  { disabled: false, value: "Europe/Belgrade", name: "(GMT+0200) Belgrade" },
  { disabled: false, value: "Europe/Berlin", name: "(GMT+0200) Berlin" },
  { disabled: false, value: "Europe/Zurich", name: "(GMT+0200) Bern" },
  { disabled: false, value: "Europe/Bratislava", name: "(GMT+0200) Bratislava" },
  { disabled: false, value: "Europe/Brussels", name: "(GMT+0200) Brussels" },
  { disabled: false, value: "Europe/Budapest", name: "(GMT+0200) Budapest" },
  { disabled: false, value: "Europe/Copenhagen", name: "(GMT+0200) Copenhagen" },
  { disabled: false, value: "Europe/Ljubljana", name: "(GMT+0200) Ljubljana" },
  { disabled: false, value: "Europe/Madrid", name: "(GMT+0200) Madrid" },
  { disabled: false, value: "Europe/Paris", name: "(GMT+0200) Paris" },
  { disabled: false, value: "Europe/Prague", name: "(GMT+0200) Prague" },
  { disabled: false, value: "Europe/Rome", name: "(GMT+0200) Rome" },
  { disabled: false, value: "Europe/Sarajevo", name: "(GMT+0200) Sarajevo" },
  { disabled: false, value: "Europe/Skopje", name: "(GMT+0200) Skopje" },
  { disabled: false, value: "Europe/Stockholm", name: "(GMT+0200) Stockholm" },
  { disabled: false, value: "Europe/Vienna", name: "(GMT+0200) Vienna" },
  { disabled: false, value: "Europe/Warsaw", name: "(GMT+0200) Warsaw" },
  { disabled: false, value: "Europe/Zagreb", name: "(GMT+0200) Zagreb" },
  { disabled: false, value: "Africa/Cairo", name: "(GMT+0200) Cairo" },
  { disabled: false, value: "Africa/Harare", name: "(GMT+0200) Harare" },
  { disabled: false, value: "Africa/Johannesburg", name: "(GMT+0200) Pretoria" },
  { disabled: false, value: "Europe/Athens", name: "(GMT+0300) Athens" },
  { disabled: false, value: "Europe/Bucharest", name: "(GMT+0300) Bucharest" },
  { disabled: false, value: "Europe/Helsinki", name: "(GMT+0300) Helsinki" },
  { disabled: false, value: "Europe/Istanbul", name: "(GMT+0300) Istanbul" },
  { disabled: false, value: "Asia/Jerusalem", name: "(GMT+0300) Jerusalem" },
  { disabled: false, value: "Europe/Kiev", name: "(GMT+0300) Kyiv" },
  { disabled: false, value: "Europe/Minsk", name: "(GMT+0300) Minsk" },
  { disabled: false, value: "Europe/Riga", name: "(GMT+0300) Riga" },
  { disabled: false, value: "Europe/Sofia", name: "(GMT+0300) Sofia" },
  { disabled: false, value: "Europe/Tallinn", name: "(GMT+0300) Tallinn" },
  { disabled: false, value: "Europe/Vilnius", name: "(GMT+0300) Vilnius" },
  { disabled: false, value: "Asia/Baghdad", name: "(GMT+0300) Baghdad" },
  { disabled: false, value: "Asia/Kuwait", name: "(GMT+0300) Kuwait" },
  { disabled: false, value: "Europe/Moscow", name: "(GMT+0300) Moscow" },
  { disabled: false, value: "Africa/Nairobi", name: "(GMT+0300) Nairobi" },
  { disabled: false, value: "Asia/Riyadh", name: "(GMT+0300) Riyadh" },
  { disabled: false, value: "Europe/Moscow", name: "(GMT+0300) St. Petersburg" },
  { disabled: false, value: "Europe/Volgograd", name: "(GMT+0400) Volgograd" },
  { disabled: false, value: "Asia/Dubai", name: "(GMT+0400) Abu Dhabi" },
  { disabled: false, value: "Asia/Baku", name: "(GMT+0400) Baku" },
  { disabled: false, value: "Asia/Muscat", name: "(GMT+0400) Muscat" },
  { disabled: false, value: "Asia/Tbilisi", name: "(GMT+0400) Tbilisi" },
  { disabled: false, value: "Asia/Yerevan", name: "(GMT+0400) Yerevan" },
  { disabled: false, value: "Asia/Tehran", name: "(GMT+0430) Tehran" },
  { disabled: false, value: "Asia/Kabul", name: "(GMT+0430) Kabul" },
  { disabled: false, value: "Asia/Karachi", name: "(GMT+0500) Islamabad" },
  { disabled: false, value: "Asia/Karachi", name: "(GMT+0500) Karachi" },
  { disabled: false, value: "Asia/Tashkent", name: "(GMT+0500) Tashkent" },
  { disabled: false, value: "Asia/Calcutta", name: "(GMT+0530) Chennai" },
  { disabled: false, value: "Asia/Calcutta", name: "(GMT+0530) Mumbai" },
  { disabled: false, value: "Asia/Calcutta", name: "(GMT+0530) New Delhi" },
  { disabled: false, value: "Asia/Calcutta", name: "(GMT+0530) Sri Jayawardenepura" },
  { disabled: false, value: "Asia/Calcutta", name: "(GMT+0530) Kolkata" },
  { disabled: false, value: "Asia/Kathmandu", name: "(GMT+0545) Kathmandu" },
  { disabled: false, value: "Asia/Almaty", name: "(GMT+0600) Almaty" },
  { disabled: false, value: "Asia/Almaty", name: "(GMT+0600) Astana" },
  { disabled: false, value: "Asia/Dhaka", name: "(GMT+0600) Dhaka" },
  { disabled: false, value: "Asia/Urumqi", name: "(GMT+0600) Urumqi" },
  { disabled: false, value: "Asia/Rangoon", name: "(GMT+0630) Rangoon" },
  { disabled: false, value: "Asia/Novosibirsk", name: "(GMT+0700) Novosibirsk" },
  { disabled: false, value: "Asia/Bangkok", name: "(GMT+0700) Bangkok" },
  { disabled: false, value: "Asia/Saigon", name: "(GMT+0700) Hanoi" },
  { disabled: false, value: "Asia/Jakarta", name: "(GMT+0700) Jakarta" },
  { disabled: false, value: "Asia/Krasnoyarsk", name: "(GMT+0700) Krasnoyarsk" },
  { disabled: false, value: "Asia/Harbin", name: "(GMT+0800) Beijing" },
  { disabled: false, value: "Asia/Chongqing", name: "(GMT+0800) Chongqing" },
  { disabled: false, value: "Asia/Hong_Kong", name: "(GMT+0800) Hong Kong" },
  { disabled: false, value: "Asia/Irkutsk", name: "(GMT+0800) Irkutsk" },
  { disabled: false, value: "Asia/Kuala_Lumpur", name: "(GMT+0800) Kuala Lumpur" },
  { disabled: false, value: "Australia/Perth", name: "(GMT+0800) Perth" },
  { disabled: false, value: "Singapore", name: "(GMT+0800) Singapore" },
  { disabled: false, value: "Asia/Taipei", name: "(GMT+0800) Ulaan Bataar" },
  { disabled: false, value: "Asia/Taipei", name: "(GMT+0800) Taipei" },
  { disabled: false, value: "Asia/Seoul", name: "(GMT+0900) Seoul" },
  { disabled: false, value: "Asia/Tokyo", name: "(GMT+0900) Tokyo" },
  { disabled: false, value: "Asia/Yakutsk", name: "(GMT+0900) Yakutsk" },
  { disabled: false, value: "Australia/Adelaide", name: "(GMT+0930) Adelaide" },
  { disabled: false, value: "Australia/Darwin", name: "(GMT+0930) Darwin" },
  { disabled: false, value: "Australia/Brisbane", name: "(GMT+1000) Brisbane" },
  { disabled: false, value: "Australia/Canberra", name: "(GMT+1000) Canberra" },
  { disabled: false, value: "Pacific/Guam", name: "(GMT+1000) Guam" },
  { disabled: false, value: "Australia/Hobart", name: "(GMT+1000) Hobart" },
  { disabled: false, value: "Australia/Melbourne", name: "(GMT+1000) Melbourne" },
  { disabled: false, value: "Pacific/Port_Moresby", name: "(GMT+1000) Port Moresby" },
  { disabled: false, value: "Australia/Sydney", name: "(GMT+1000) Sydney" },
  { disabled: false, value: "Asia/Vladivostok", name: "(GMT+1000) Vladivostok" },
  { disabled: false, value: "Asia/Magadan", name: "(GMT+1100) Magadan" },
  { disabled: false, value: "Pacific/Noumea", name: "(GMT+1100) New Caledonia" },
  { disabled: false, value: "Pacific/Guadalcanal", name: "(GMT+1100) Solomon Is. " },
  { disabled: false, value: "Pacific/Norfolk", name: "(GMT+1100) Norfolk" },
  { disabled: false, value: "Pacific/Auckland", name: "(GMT+1200) Auckland" },
  { disabled: false, value: "Pacific/Fiji", name: "(GMT+1200) Fiji" },
  { disabled: false, value: "Asia/Kamchatka", name: "(GMT+1200) Kamchatka" },
  { disabled: false, value: "Asia/Kamchatka", name: "(GMT+1200) Marshall Is." },
  { disabled: false, value: "Pacific/Auckland", name: "(GMT+1200) Wellington" },
  { disabled: false, value: "Pacific/Tongatapu", name: "(GMT+1300) Nuku'alofa" },
  { disabled: true, value: "", name: "--------------------" },
  { disabled: false, value: "GMT -12:00", name: "GMT -12:00" },
  { disabled: false, value: "GMT -11:00", name: "GMT -11:00" },
  { disabled: false, value: "GMT -10:00", name: "GMT -10:00" },
  { disabled: false, value: "GMT -9:00", name: "GMT -9:00" },
  { disabled: false, value: "GMT -8:00", name: "GMT -8:00" },
  { disabled: false, value: "GMT -7:00", name: "GMT -7:00" },
  { disabled: false, value: "GMT -6:00", name: "GMT -6:00" },
  { disabled: false, value: "GMT -5:00", name: "GMT -5:00" },
  { disabled: false, value: "GMT -4:00", name: "GMT -4:00" },
  { disabled: false, value: "GMT -3:00", name: "GMT -3:00" },
  { disabled: false, value: "GMT -2:00", name: "GMT -2:00" },
  { disabled: false, value: "GMT -1:00", name: "GMT -1:00" },
  { disabled: false, value: "GMT", name: "GMT" },
  { disabled: false, value: "UTC", name: "UTC" },
  { disabled: false, value: "GMT +1:00", name: "GMT +1:00" },
  { disabled: false, value: "GMT +2:00", name: "GMT +2:00" },
  { disabled: false, value: "GMT +3:00", name: "GMT +3:00" },
  { disabled: false, value: "GMT +4:00", name: "GMT +4:00" },
  { disabled: false, value: "GMT +5:00", name: "GMT +5:00" },
  { disabled: false, value: "GMT +6:00", name: "GMT +6:00" },
  { disabled: false, value: "GMT +7:00", name: "GMT +7:00" },
  { disabled: false, value: "GMT +8:00", name: "GMT +8:00" },
  { disabled: false, value: "GMT +9:00", name: "GMT +9:00" },
  { disabled: false, value: "GMT +10:00", name: "GMT +10:00" },
  { disabled: false, value: "GMT +11:00", name: "GMT +11:00" },
  { disabled: false, value: "GMT +12:00", name: "GMT +12:00" },
  { disabled: false, value: "GMT +13:00", name: "GMT +13:00" }
];

export default {};
